YUI.add('nfl-swf',function(Y,NAME){var Event=Y.Event,SWFDetect=Y.SWFDetect,Lang=Y.Lang,uA=Y.UA,Node=Y.Node,Escape=Y.Escape,FLASH_CID="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000",FLASH_TYPE="application/x-shockwave-flash",FLASH_VER="10.0.22",EXPRESS_INSTALL_URL="http://fpdownload.macromedia.com/pub/flashplayer/update/current/swf/autoUpdater.swf?"+Math.random(),EVENT_HANDLER="SWF.eventHandler",possibleAttributes={align:"",allowFullScreen:"",allowFullScreenInteractive:"",allowNetworking:"",allowScriptAccess:"",base:"",bgcolor:"",loop:"",menu:"",name:"",play:"",quality:"",salign:"",scale:"",tabindex:"",wmode:""};function SWF(p_oElement,swfURL,p_oAttributes){this._id=Y.guid("yuiswf");var _id=this._id;var oElement=Node.one(p_oElement);var p_oAttributes=p_oAttributes||{};var flashVersion=p_oAttributes.version||FLASH_VER;var flashVersionSplit=(flashVersion+'').split(".");var isFlashVersionRight=SWFDetect.isFlashVersionAtLeast(parseInt(flashVersionSplit[0],10),parseInt(flashVersionSplit[1],10),parseInt(flashVersionSplit[2],10));var canExpressInstall=(SWFDetect.isFlashVersionAtLeast(8,0,0));var shouldExpressInstall=canExpressInstall&&!isFlashVersionRight&&p_oAttributes.useExpressInstall;var flashURL=(shouldExpressInstall)?EXPRESS_INSTALL_URL:swfURL;var objstring='<object ';var w,h;var flashvarstring="yId="+Y.id+"&YUISwfId="+_id+"&YUIBridgeCallback="+EVENT_HANDLER+"&allowedDomain="+document.location.hostname;var isIE11orAbove=Object.hasOwnProperty.call(window,"ActiveXObject")&&!window.ActiveXObject;Y.SWF._instances[_id]=this;if(oElement&&(isFlashVersionRight||shouldExpressInstall)&&flashURL){objstring+='id="'+_id+'" ';if(uA.ie&&!isIE11orAbove){objstring+='classid="'+FLASH_CID+'" ';}else{objstring+='type="'+FLASH_TYPE+'" data="'+Escape.html(flashURL)+'" ';}
w="100%";h="100%";objstring+='width="'+w+'" height="'+h+'">';if(uA.ie&&!isIE11orAbove){objstring+='<param name="movie" value="'+Escape.html(flashURL)+'"/>';}
for(var attribute in p_oAttributes.fixedAttributes){if(possibleAttributes.hasOwnProperty(attribute)){objstring+='<param name="'+Escape.html(attribute)+'" value="'+Escape.html(p_oAttributes.fixedAttributes[attribute])+'"/>';}}
for(var flashvar in p_oAttributes.flashVars){var fvar=p_oAttributes.flashVars[flashvar];if(Lang.isString(fvar)){flashvarstring+="&"+Escape.html(flashvar)+"="+Escape.html(encodeURIComponent(fvar));}}
if(flashvarstring){objstring+='<param name="flashVars" value="'+flashvarstring+'"/>';}
objstring+="</object>";oElement.set("innerHTML",objstring);this._swf=Node.one("#"+_id);}else{var event={};event.type="wrongflashversion";this.publish("wrongflashversion",{fireOnce:true});this.fire("wrongflashversion",event);}}
SWF._instances=SWF._instances||{};SWF.eventHandler=function(swfid,event){SWF._instances[swfid]._eventHandler(event);};SWF.prototype={_eventHandler:function(event){if(event.type==="swfReady"){this.publish("swfReady",{fireOnce:true});this.fire("swfReady",event);}else if(event.type==="log"){}else{this.fire(event.type,event);}},callSWF:function(func,args){if(!args){args=[];}
if(this._swf._node[func]){return(this._swf._node[func].apply(this._swf._node,args));}else{return null;}},toString:function(){return"SWF "+this._id;}};Y.augment(SWF,Y.EventTarget);Y.SWF=SWF;},'3.10.3',{"requires":["event-custom","node","swfdetect","escape"]});;YUI.add("nfl-video-swf",function(Y){"use strict";var NFLVideo=Y.namespace("NFL.Video"),SWF_PATH=Y.config.groups.nflui.base+"nfl-video-swf/assets/player.swf?v="+Y.config.win.nfl_ui_version,PlayerEvent=NFLVideo.PlayerEvent,yLangIsUndefined=Y.Lang.isUndefined,adFlashVars={type:"adType",flashAdTag:"adTag",setting:"adSetting",ratio:"adRatio"},proxiedFlashVars=["omniture","configURL","playerName","related","relatedValue","contentURL","contentId","channelId","showBranding"];NFLVideo.SWFPlayer=Y.Base.create("nfl-video-swf",NFLVideo.Base,[],{initializer:function(){var host=this.get("host");if(host.get("rendered")){this._uiRenderSWF();}else{this._afterRenderHandler=Y.Do.after(this._uiRenderSWF,host,"syncUI",this);}},play:function(){this._swf.callSWF("playVideo",[]);},pause:function(){this._swf.callSWF("pauseVideo",[]);},seek:function(toTime){this._swf.callSWF("seekVideo",[toTime]);},loadJSON:function(url,autoplay){this._swf.callSWF("loadJSON",[url,autoplay]);},loadContentId:function(url,autoplay){this._swf.callSWF("loadContentId",[url,autoplay]);},destructor:function(){if(this._afterRenderHandler){Y.Do.detach(this._afterRenderHandler);}
if(this._swf){this._swf.destroy();}
if(this._continusousChangeHandler){this._continusousChangeHandler.detach();this._nextVideoChangeHandler.detach();}},_afterContinuousChange:function(event){this._swf.callSWF('setIsContinuousPlayEnabled',[event.newVal]);},_afterNextVideoChange:function(event){var nv=event.newVal;this._swf.callSWF("setNextVideo",[nv.ecmId,nv.headline,nv.thumbnail]);},_afterInitialized:function(){var host=this.get("host"),hostAttrs=host.getAttrs();if(hostAttrs.continuous){this._afterContinuousChange({newVal:true});}
if(hostAttrs.nextVideo.ecmId){this._afterNextVideoChange({newVal:hostAttrs.nextVideo});}
this._continusousChangeHandler=host.after("continuousChange",this._afterContinuousChange,this);this._nextVideoChangeHandler=host.after("nextVideoChange",this._afterNextVideoChange,this);this.fire(PlayerEvent.INITIALIZED);},_getFlashVars:function(flashVars){var host=this.get("host"),attrs=host.getAttrs(),ads=attrs.ads;if(ads){Y.Object.each(adFlashVars,function(flashVarName,configName){var value=ads[configName];if(!yLangIsUndefined(value)){flashVars[flashVarName]=String(ads[configName]);}});if(host.companionSizes&&host.companionSizes.length){flashVars.companionSize=host.companionSizes.join(",");}}
Y.Array.each(proxiedFlashVars,function(flashVarName){var value=attrs[flashVarName];if(!yLangIsUndefined(value)&&value!==""){flashVars[flashVarName]=String(value);}});if(attrs.debugMode){flashVars.debugMode="true";}
if(attrs.autoplay){flashVars.autoplay="true";}
if(attrs.isContinousManual){flashVars.playlistControl="js";}
if(attrs.chromeless){flashVars.chromeless="true";}
return flashVars;},_uiRenderSWF:function(){var swf=this._swf=new Y.SWF(this.get("host").get("contentBox"),SWF_PATH,{fixedAttributes:{allowScriptAccess:"always",allowFullScreen:"true",wmode:"opaque",bgcolor:"#000000"},flashVars:this.get("flashVars")});Y.Object.each(PlayerEvent,function(eventName){var config={emitFacade:true};if(eventName!==PlayerEvent.INITIALIZED){Y.mix(config,{bubbles:true,broadcast:2});}
swf.publish(eventName,config);});swf.once(PlayerEvent.INITIALIZED,this._afterInitialized,this);swf.addTarget(this);}},{NS:"player",ATTRS:{flashVars:{value:{},getter:"_getFlashVars"}}});if(!Y.Lang.isFunction(Y.SWF.prototype.destroy)){Y.SWF.prototype.destroy=function(){this.detachAll();this._swf.remove(true);delete this._swf;delete Y.SWF._instances[this._id];};}},"3.4.1",{requires:["base-build","nfl-video-base","nfl-swf"]});