(function(){YUI.add("header-2012-base",(function(Y){"use strict";var headerNode;headerNode=Y.one("#header-2012");window.Y.namespace("NFL.Header2012").headerNode=headerNode;Y.namespace("NFL.Header2012").LoadHeader=function(){var bbx,_ref,_ref2,_subContentHTML,headerIncludesURI,headerRequest;Y.one("body").delegate("focus",function(e){Y.Global.fire("header:focus",e);},"a");Y.on("contentready",(function(){var searchBox,setPlaceholderText;searchBox=Y.one("#header-2012 input[name=query]");searchBox.on("focus",function(e){if(this.get("value")===this.getAttribute("data-placeholder")){return this.set("value","");}});setPlaceholderText=function(e){if(this.get("value")===""){return this.set("value",this.getAttribute("data-placeholder"));}};searchBox.once('focus',function(e){Y.use('autocomplete',function(){searchBox.plug(Y.Plugin.AutoComplete,{resultHighlighter:'phraseMatch',resultListLocator:'ac.q',minQueryLength:2,queryDelay:1,source:'http://search.nfl.com/autocomplete/?q={query}&n=5&callbackName={callback}'});});});searchBox.on("blur",setPlaceholderText);return Y.bind(setPlaceholderText,searchBox)();}),"#header-2012");Y.on('io:success',loadHeaderIncludes,Y);Y.on('io:failure',loadHeaderIncludesFail,Y);function loadHeaderIncludes(id,o){var includes=Y.Node.create(o.response||o.responseText),navPlaceholders=Y.all('.nav-place-holder'),navPHLength=navPlaceholders.size();navPlaceholders.each(function(item,index){var elemId=item.get('id');if(includes.one('#'+elemId)){try{item.replace(Y.Node.create(includes.one('#'+elemId).get('innerHTML')));}catch(err){console.log('Header: '+err.message);}
if((index+1)===navPHLength){runRest();}}});function runRest(){if((_ref=headerNode.one(".top-nav-items .b-nav-group"))!=null){_ref.setStyle("borderLeft","none");}
headerNode.delegate("click",(function(e){var linkNode,linkText,linkValue,navGroupId,s_analytics,_ref2;linkNode=e.currentTarget;linkNode.set("hideFocus",true);if(/\w/.test(linkNode.getAttribute("href"))||linkNode.getAttribute("href")==="/"){navGroupId=(_ref2=linkNode.ancestor(".b-nav-group"))!=null?_ref2.getAttribute("id"):void 0;if(navGroupId){linkText=linkNode.get("text").toLowerCase().replace(/[\W\s]/g,"");linkValue="tn-"+navGroupId.replace("b-nav-group-","")+"-"+linkText;s_analytics=s_gi(s_account);s_analytics.tl(this,'o',linkText,{linkTrackVars:"events,eVar12",linkTrackEvents:"event50",events:"event50",eVar12:linkValue});if(window.location.href.indexOf("headerDebug")>-1){return e.halt(true);}}}else{if(!linkNode.hasClass("sub-content"))return e.halt(true);}}),"a");try{if(Y.UA.ie&&nfl.ss){bbx=nfl.ss.get("boundingBox");bbx.removeClass("yui3-scorestrip-fixed");bbx.removeClass("yui3-scorestrip-iframe-fixed");nfl.ss.syncUI();headerNode.setStyle("zIndex",2000);}}catch(error){console.error(error);}
window.loadHeaderIncludesCompleted=true;}}
function loadHeaderIncludesFail(){console.error('->header includes failed to load')
return;}
_ref2=Y.one("div#header-2012-subcontent");if(_ref2){_subContentHTML=_ref2.getContent();_ref2.remove();loadHeaderIncludes(1,{responseText:_subContentHTML});}else{headerIncludesURI='/widgets/navigation/header-2012/header-includes.html';headerRequest=Y.io(headerIncludesURI);}};}),"1.0.0",{requires:["node","transition","io"]});}).call(this);;(function(){YUI.add("header-anim-plugins",(function(Y){"use strict";var SlideDownPlugin,SlideLeftPlugin,SlideRightPlugin,SlideUpPlugin;SlideDownPlugin=(function(){function SlideDownPlugin(config){this._node=config.host;}
SlideDownPlugin.prototype.run=function(height,callback){var anim,node,_ref;node=this._node;height=height||260;callback=callback||function(){};if((_ref=node.getData("anim"))!=null)_ref.stop();node.setStyles({height:"0px",display:"block",overflow:"hidden","opacity":1});anim=new Y.Anim({node:node,to:{height:""+height+"px"},duration:0.5,easing:Y.Easing.easeIn,on:{end:callback}});node.setData("anim",anim);return anim.run();};return SlideDownPlugin;})();SlideDownPlugin.NS="slideDown";Y.namespace("NFL.Header2012").SlideDownPlugin=SlideDownPlugin;SlideUpPlugin=(function(){function SlideUpPlugin(config){this._node=config.host;}
SlideUpPlugin.prototype.run=function(height,callback){var anim,node,_ref;node=this._node;height=height||0;callback=callback||function(){};if((_ref=node.getData("anim"))!=null)_ref.stop();node.setStyles({'visibility':'visible'});anim=new Y.Anim({node:node,to:{opacity:0,height:'0px'},easing:Y.Easing.easeOut,duration:0.3,on:{end:callback}});node.setData("anim",anim);return anim.run();};return SlideUpPlugin;})();SlideUpPlugin.NS="slideUp";Y.namespace("NFL.Header2012").SlideUpPlugin=SlideUpPlugin;SlideRightPlugin=(function(){function SlideRightPlugin(config){this._node=config.host;}
SlideRightPlugin.prototype.run=function(width,reverse){var anim,node,_ref;node=this._node;width=width||170;reverse=reverse||false;if((_ref=node.getData("anim"))!=null)_ref.stop();if(!reverse){node.setStyles({visibility:'visible',width:'0px'});}
anim=new Y.Anim({node:node,from:{width:"0px"},to:{width:""+width+"px"},easing:Y.Easing.easeInStrong,duration:0.5,reverse:reverse});node.setData("anim",anim);return anim.run();};SlideRightPlugin.NS="slideRight";Y.namespace("NFL.Header2012").SlideRightPlugin=SlideRightPlugin;return SlideRightPlugin;})();return SlideLeftPlugin=(function(){function SlideLeftPlugin(config){this._node=config.host;}
SlideLeftPlugin.prototype.run=function(fromLeft,toLeft,width,reverse){var anim,node,_ref;node=this._node;width=width||170;reverse=reverse||false;if((_ref=node.getData("anim"))!=null)_ref.stop();if(!reverse){node.setStyles({visibility:'visible',width:'0px'});}
anim=new Y.Anim({node:node,from:{left:""+fromLeft+"px",width:"0px"},to:{left:""+toLeft+"px",width:""+width+"px"},easing:Y.Easing.easeInStrong,duration:0.5,reverse:reverse,on:{start:function(){var xy;xy=node.getXY();node.setStyle("position","fixed");return node.setXY(xy);},end:function(){var xy;xy=node.getXY();node.setStyle("position","absolute");return node.setXY(xy);}}});node.setData("anim",anim);return anim.run();};SlideLeftPlugin.NS="slideLeft";Y.namespace("NFL.Header2012").SlideLeftPlugin=SlideLeftPlugin;return SlideLeftPlugin;})();}),"1.0.0",{requires:["node","anim"]});}).call(this);;(function(){YUI.add("hp-teams-links",(function(Y){"use strict";return Y.namespace("NFL.Header2012").TeamLinksGenerator={render:function(containerNode,urlTemplate){var href,target,teamNode,teamLink;containerNode=Y.one(containerNode);if(containerNode&&containerNode.one("div.teams"))return;Y.NFLTeam.load(function(event){var season=event.season;var NFLTeams=Y.NFLTeamsBySeason[season];var NFLDivisions=Y.NFLDivisionsBySeason[season];var template=["<div class=\"teams\">"];Y.Array.each(["AFC","NFC"],function(conf){template.push("<div class=\""+conf.toLowerCase()+"\">");Y.Array.each(["East","North","South","West"],function(div){template.push("<div class=\"column\">");template.push("<div class=\"conference-label\">"+[conf.toLowerCase(),div.toLowerCase()].join(" ")+"</div>");template.push("<ul class=\"section\">");Y.Array.each(NFLDivisions[[conf,div].join(" ")],function(abbr){template.push("<li><a href=\"#\" data-abbr=\""+abbr+"\">"+NFLTeams[abbr].get("fullName")+"</a></li>");});template.push("</ul></div>");});template.push("</div>");});template.push("</div>");containerNode.setContent(template.join(""));teamNode=containerNode.one("div.teams");target="_blank";Y.Object.each(NFLTeams,function(team,abbr){if(urlTemplate){if(urlTemplate.indexOf("nfl.com/")>-1){target="";}
href=Y.Lang.sub(urlTemplate,team.getAttrs());}else{href=team.get("url");}
if(teamNode!=null){teamLink=teamNode.one("a[data-abbr="+abbr+"]");if(teamLink){teamLink.setAttribute("href",href);}}});});}};}),"1.0.0",{requires:["node","substitute","data-teams"]});}).call(this);;(function(){var Constants=nfl.constants;YUI.add("header-main-nav",(function(Y){"use strict";var Animatable;Animatable=(/nfl.com$/i.test(window.location.hostname)||/nfl.net$/i.test(window.location.hostname))?true:false;return Y.namespace("NFL.Header2012").ObserveMainNav=function(){var getHighestZIndex,headerNode,navNode,toggleContent,_ref,_hoverBg,_activeBg;headerNode=window.Y.namespace("NFL.Header2012").headerNode;navNode=headerNode.one(".main-nav");_hoverBg=new Image();_hoverBg.src=Constants.STYLE_PATH+"/img/header-2012/nav-bg-hover.png";_activeBg=new Image();_activeBg.src=Constants.STYLE_PATH+"/img/header-2012/nav-bg-active.png";getHighestZIndex=function(){var zIndex;zIndex=headerNode.getData("contentZIndex")||2;headerNode.setData("contentZIndex",zIndex+1);return zIndex+1;};toggleContent=function(contentNode,show){if(!contentNode){return;}
var teamsContainerNode,shopNode,shopData,shopDataJson,shopContents,_ref,_ref10,_ref2,_ref3,_ref4,_ref5,_ref6,_ref7,_ref8,_ref9;if(show){teamsContainerNode=contentNode.one("div.teams-ondemand");shopNode=contentNode.one('.shop-navigation-ad')
if(teamsContainerNode){Y.NFL.Header2012.TeamLinksGenerator.render(teamsContainerNode,teamsContainerNode.getAttribute("data-urltemplate"));}
if(shopNode){if(!shopNode.hasClass('loaded')){shopData=new Y.ShopData({'location':'navigation','teamAbbr':true});shopData.on('shop-data:response',function(event){if(event.details[0]==='success'){shopDataJson=shopData.getShopData();if(shopDataJson.length!==0){shopContents='<a href="{redirectUrl}"><img src="{imageUrl}" alt="{altText}"/></a>';shopContents=Y.Lang.sub(shopContents,shopDataJson[0]);shopNode.addClass('loaded');shopNode.append(shopContents);}}},this);}}
if(!contentNode.slideDown){Y.Global.fire("header:hideContent");contentNode.plug(Y.NFL.Header2012.SlideDownPlugin);}
if(contentNode.get("offsetHeight")!==260){contentNode.addClass("active");return(_ref=contentNode.slideDown)?_ref.run(260,function(){var _ref2;if(Y.UA.mobile){return(_ref2=contentNode.one("div.close-content"))?_ref2.setStyles({visibility:"visible",zIndex:getHighestZIndex()}):void 0;}}):void 0;}}else{if(!contentNode.slideUp){contentNode.plug(Y.NFL.Header2012.SlideUpPlugin);}
if((_ref2=contentNode.all("div.sub-content"))){_ref2.setStyle("display","none");}
if((_ref3=contentNode.all("a.expanded > i.tip"))){_ref3.setStyle("display","none");}
if((_ref4=contentNode.all("a.expanded > i"))){_ref4.removeClass("close-white");}
if((_ref5=contentNode.all("a.expanded > i"))){_ref5.addClass("more");}
if((_ref6=contentNode.all("a.expanded"))){_ref6.removeClass("expanded");}
if(Y.UA.mobile){if((_ref7=contentNode.one("div.close-content"))){_ref7.setStyle("visibility","hidden");}}
contentNode.removeClass("active");if((_ref8=contentNode.slideUp))_ref8.run();return(_ref9=contentNode.ancestor(".b-nav-group"))?(_ref10=_ref9.one("div.top-label"))?_ref10.removeClass("active"):void 0:void 0;}};function hideAll(){navNode.all("div.content.active").each(function(contentNode){toggleContent(contentNode,false);});}
if(Modernizr.datauri){headerNode.all("div.top-label").addClass("no-datauri");if((_ref=headerNode.one("div.faux-3d-strip"))){_ref.addClass("no-datauri");}}
function mouseEnterHandler(e){var contentNode,listNode,topLabelNode,zIndex,_ref2;if(window.location.href.indexOf("headerDebug")>-1)return;listNode=e.currentTarget;if((_ref2=listNode.getData("laterFn")))_ref2.cancel();contentNode=listNode.one("> div.content");topLabelNode=listNode.one("div.top-label");if(!(topLabelNode?topLabelNode.hasClass("no-touch"):void 0)){if(!Y.UA.mobile){if(topLabelNode)topLabelNode.addClass("no-touch");}}
zIndex=getHighestZIndex();if(contentNode){contentNode.setStyle("zIndex",zIndex);}
if(Animatable){return listNode.setData("laterFn",Y.later(100,this,function(){return toggleContent(contentNode,true);}));}};headerNode.delegate("mouseenter",mouseEnterHandler,".main-nav .b-nav-group");headerNode.delegate("focus",mouseEnterHandler,".main-nav .b-nav-group");headerNode.delegate("mouseenter",function(e){var contentNode,topLabelNode,_ref2;if(window.location.href.indexOf("headerDebug")>-1)return;contentNode=e.currentTarget;topLabelNode=(_ref2=contentNode.ancestor(".b-nav-group"))?_ref2.one("div.top-label"):void 0;return topLabelNode?topLabelNode.addClass("active"):void 0;},".main-nav .b-nav-group > div.content");headerNode.delegate("touchstart",function(e){var closeNode,contentNode;if(!Animatable)return;e.halt(true);closeNode=e.currentTarget;contentNode=closeNode.ancestor("div.content");if(contentNode)return toggleContent(contentNode,false);},"div.close-content");headerNode.delegate("mouseleave",function(e){var laterFn,listNode,_ref2;if(window.location.href.indexOf("headerDebug")>-1)return;listNode=e.currentTarget;if((_ref2=listNode.getData("laterFn")))_ref2.cancel();laterFn=Y.later(200,this,function(){var contentNode;contentNode=listNode.one("> div.content");return toggleContent(contentNode,false);});return listNode.setData("laterFn",laterFn);},".main-nav .b-nav-group");headerNode.delegate("touchstart",(function(e){var contentNode,linkNode,listNode,_ref2;if(!Animatable)return;if(!e.currentTarget.one('.top-nav-down-arrow')){return;}
e.halt(true);linkNode=e.currentTarget;if((_ref2=linkNode.ancestor("div.top-label"))){_ref2.toggleClass("active");}
listNode=linkNode.ancestor("li");listNode.siblings().each(function(elm){var contentNode,_ref3;contentNode=elm.one("div.content");if(!contentNode){return;}
if((_ref3=elm.one("div.top-label"))){_ref3.removeClass("active");}
if(!contentNode.slideUp){contentNode.plug(Y.NFL.Header2012.SlideUpPlugin);}
if(contentNode.get("offsetHeight")>0){return contentNode.slideUp.run();}});contentNode=listNode.one("div.content");if(contentNode){return toggleContent(contentNode,(contentNode.get("offsetHeight")>100?false:true));}}),"a.top-nav");Y.Global.on("header:focus",function(e){if(!navNode.contains(e.currentTarget)){hideAll();}});Y.Global.on("header:hideContent",hideAll);};}),"1.0.0",{requires:["node","event-mouseenter","event-touch","header-2012-base","header-anim-plugins","plugin","event-custom"]});}).call(this);;(function(){YUI.add("header-secondary-nav",(function(Y){"use strict";Y.on('contentready',function(){var announcementNodes=Y.all('.announcement .list-items li'),announcementNodeContainer=Y.one('.announcement .list-items ul'),moveIndex=0,moveDistance=-24,movement;if(announcementNodes.size()>1){Y.later(5000,this,function(){if((moveIndex+1)===announcementNodes.size()){moveIndex=movement=0;}else{moveIndex++;movement=moveIndex*moveDistance;}
announcementNodeContainer.transition({'duration':0.5,'easing':'ease-in','top':movement+'px'});},[],true);}},'#announcement-ph')
return Y.namespace("NFL.Header2012").ObserveSecondaryNav=function(){var headerNode,navNode,hideSecondaryNavContent,showSecondaryNavContent,currentExpandedContentNode;headerNode=window.Y.namespace("NFL.Header2012").headerNode;navNode=headerNode.one(".secondary-nav");hideSecondaryNavContent=function(e){var listNode,_ref;listNode=e.currentTarget.ancestor("ul");if((_ref=listNode.all("div.top-label"))!=null){setTimeout(function(){_ref.setStyle("top","0px")},25);}
return listNode.all("div.content").each(function(contentNode){var _ref2;if(!contentNode.slideUp){contentNode.plug(Y.NFL.Header2012.SlideUpPlugin);}
contentNode.removeClass("active");return(_ref2=contentNode.slideUp)!=null?_ref2.run(0,function(){return contentNode.setStyle("display","none");}):void 0;});};showSecondaryNavContent=function(e){var contentNode,height,listItemNode,tab,teamsContainerNode,_ref;tab=e.currentTarget;tab.addClass("active");listItemNode=tab.ancestor("li");contentNode=listItemNode&&listItemNode.one("div.content");if(currentExpandedContentNode){hideSecondaryNavContent({currentTarget:currentExpandedContentNode});currentExpandedContentNode=null;}
currentExpandedContentNode=contentNode;if(!contentNode){return;}
if(contentNode.get("offsetHeight")>30){hideSecondaryNavContent(e);return;}
contentNode.setStyles({display:"block",visibility:"visible"});contentNode.addClass("active");height=contentNode.getAttribute("data-height");if(!height){if(contentNode.get("offsetHeight")>30){height=contentNode.get("offsetHeight");}
contentNode.setAttribute("data-height",height);}
teamsContainerNode=contentNode.one("div.teams-ondemand");if(teamsContainerNode){Y.NFL.Header2012.TeamLinksGenerator.render(teamsContainerNode,teamsContainerNode.getAttribute("data-urltemplate"));}
if(!contentNode.slideDown){contentNode.plug(Y.NFL.Header2012.SlideDownPlugin);}
return(_ref=contentNode.slideDown)!=null?_ref.run(height,function(){}):void 0;};function hideAll(){headerNode.all("div.secondary-nav div.content").each(function(contentNode){hideSecondaryNavContent({currentTarget:contentNode});});}
if(!Y.UA.mobile){headerNode.all("div.secondary-nav ul.secondary-nav-items > li > div.top-label").addClass("no-touch");}
headerNode.delegate("click",showSecondaryNavContent,"div.secondary-nav ul.secondary-nav-items > li > div.top-label");headerNode.delegate("focus",showSecondaryNavContent,"div.secondary-nav ul.secondary-nav-items > li > div.top-label");headerNode.delegate("mouseleave",hideSecondaryNavContent,"div.secondary-nav ul.secondary-nav-items > li");headerNode.delegate("click",hideSecondaryNavContent,"div.secondary-nav i.close");Y.Global.on("header:focus",function(e){if(!navNode.contains(e.currentTarget)){hideAll();}});Y.Global.on("header:hideContent",hideAll);};}),"1.0.0",{requires:["node","event-mouseenter","event-touch","header-2012-base","header-anim-plugins","plugin","event-custom"]});}).call(this);;(function(){YUI.add("header-tertiary-content",(function(Y){"use strict";return Y.namespace("NFL.Header2012").ObserveTertiaryContent=function(){var headerNode,toggleSubContent,currentExpandedContentNode;toggleSubContent=function(linkNode){var anchorNode,anchorXLocation,anchorYLocation,fromLeft,iconNode,reverse,subContentNode,teamsContainerNode,tipNode,toLeft,width,_ref,_ref2,_ref3;anchorNode=linkNode.ancestor(".sub-content-anchor");if(!anchorNode)anchorNode=linkNode.ancestor("div.column");subContentNode=(_ref=linkNode.ancestor("li"))!=null?_ref.one("div.sub-content"):void 0;if(!subContentNode.slideRight){subContentNode.plug(Y.NFL.Header2012.SlideRightPlugin);}
if(!subContentNode.slideLeft){subContentNode.plug(Y.NFL.Header2012.SlideLeftPlugin);}
iconNode=linkNode.one("i");tipNode=linkNode.one("i.tip");if(iconNode!=null?iconNode.hasClass("more"):void 0){iconNode.removeClass("more");iconNode.addClass("close-white");linkNode.addClass("expanded");if(anchorNode&&subContentNode){currentExpandedContentNode=subContentNode;teamsContainerNode=subContentNode.one("div.teams-ondemand");if(teamsContainerNode){Y.NFL.Header2012.TeamLinksGenerator.render(teamsContainerNode,teamsContainerNode.getAttribute("data-urltemplate"));}
anchorXLocation=anchorNode.getX();anchorYLocation=subContentNode.ancestor("div.content").getY();if(Y.UA.ie&&Y.UA.ie<=7){linkNode.setStyles({position:"relative",zIndex:10});}
subContentNode.setStyles({position:"absolute",display:"block",visibility:"hidden",overflow:"hidden",zIndex:8});width=subContentNode.getAttribute("data-width")||170;if(!tipNode.hasClass("tip-left")){subContentNode.setXY([anchorXLocation+anchorNode.get("offsetWidth"),anchorYLocation]);if((_ref2=subContentNode.slideRight)!=null)_ref2.run(width);}else{fromLeft=parseInt(anchorXLocation,10);toLeft=parseInt(anchorXLocation-width,10);subContentNode.setXY([fromLeft,anchorYLocation]);if((_ref3=subContentNode.slideLeft)!=null){_ref3.run(fromLeft,toLeft,width);}}
return tipNode!=null?tipNode.setStyle("display","block"):void 0;}}else if(iconNode!=null?iconNode.hasClass("close-white"):void 0){iconNode.removeClass("close-white");iconNode.addClass("more");linkNode.removeClass("expanded");if(tipNode!=null)tipNode.setStyle("display","none");reverse=true;width=subContentNode.getAttribute("data-width")||170;if(!tipNode.hasClass("tip-left")){return subContentNode.slideRight.run(width,reverse);}else{toLeft=parseInt(subContentNode.getX(),10);fromLeft=parseInt(anchorNode.getX(),10);return subContentNode.slideLeft.run(fromLeft,toLeft,width,reverse);}}};headerNode=window.Y.namespace("NFL.Header2012").headerNode;function subContentClickHandler(e){var expandedLinkNodes,linkNode,targetLinkNodeId;e.halt(true);linkNode=e.currentTarget;if(linkNode.hasClass("expanded")){return;}
expandedLinkNodes=headerNode.all("a.sub-content.expanded");if(expandedLinkNodes.size()>0){targetLinkNodeId=linkNode.get("id");expandedLinkNodes.each(function(expandedLinkNode){if(targetLinkNodeId!==expandedLinkNode.get("id")){return toggleSubContent(expandedLinkNode);}});}
return toggleSubContent(linkNode);}
headerNode.delegate("click",subContentClickHandler,"a.sub-content");headerNode.delegate("focus",subContentClickHandler,"a.sub-content");Y.Global.on("header:focus",function(e){if(!currentExpandedContentNode){return;}
var linkNode=e.currentTarget,contentOutOfFocus=!currentExpandedContentNode.contains(linkNode);if(contentOutOfFocus){toggleSubContent(currentExpandedContentNode.ancestor("li").one("a"));currentExpandedContentNode=null;}});headerNode.delegate("mouseleave",(function(e){var subContentNode;subContentNode=e.currentTarget;return toggleSubContent(subContentNode.ancestor("li").one("a"));}),"div.sub-content");return headerNode.delegate("click",(function(e){var closeIcon,subContentNode;closeIcon=e.currentTarget;subContentNode=closeIcon.ancestor(".sub-content");return subContentNode!=null?subContentNode.setStyle("display","none"):void 0;}),"i.close");};}),"1.0.0",{requires:["node","event-mouseenter","header-2012-base","header-anim-plugins","plugin","hp-teams-links"]});}).call(this);;(function(){YUI.add("header-static-team-bar",(function(Y){"use strict";var mainTemplate;return Y.namespace("NFL.Header2012").HeaderStaticTeamBar=function(){if(Y.one('#team-sites-header-bar')!==null){return;}
Y.NFLTeam.load(function(){var teamLinks=[];Y.Array.each(["AFC","NFC"],function(conf){Y.Array.each(["East","North","South","West"],function(div){Y.Array.each(Y.NFLDivisions[[conf,div].join(" ")],function(abbr){teamLinks.push('<a href="'+Y.NFLTeams[abbr].get('url')+'" class="'+abbr.toLowerCase()+'" target="_blank" aria-label="'+Y.NFLTeams[abbr].get('nickname')+'"></a>');});});});mainTemplate=['<div id="team-sites-header-bar" class="dd" role="navigation">','<div class="team-sites-header-bar-logo-container">',teamLinks.join(''),'</div>','<a href="#" class="team-sites-header-bar-dd-tab" data-clickname="header-2012-teams-dropdown-tab" aria-hidden="true" tabindex="-1"></a>','</div>'];var headerBar=Y.Node.create(mainTemplate.join(''));var d=new Date();var nextMonth=new Date(d.getTime()+30*24*60*60*1000);if(Y.Cookie.get('navigationTeamsDDOpen')==='false'){headerBar.one('.team-sites-header-bar-dd-tab').addClass('closed');headerBar.setStyle('marginTop','-40px');Y.one('body').setStyle('backgroundPosition','center 0px');Y.Cookie.set('navigationTeamsDDOpen','false',{path:"/",domain:".nfl.com",expires:nextMonth});}else{Y.Cookie.set('navigationTeamsDDOpen','true',{path:"/",domain:".nfl.com",expires:nextMonth});Y.one('body').setStyle('backgroundPosition','center 40px');}
headerBar.delegate('click',function(e){var elem=e.currentTarget,anim;e.preventDefault();if(elem.hasClass('closed')){elem.removeClass('closed');if(Y.UA.ie>0){Y.one('body').setStyle('backgroundPosition','center 40px');headerBar.setStyle('marginTop','0px');}else{Y.one('body').transition({'backgroundPosition':'center 40px','duration':'0.5'});headerBar.transition({'duration':'0.5','marginTop':'0px'});}
Y.Cookie.set('navigationTeamsDDOpen','true',{path:"/",domain:".nfl.com",expires:nextMonth});}else{elem.addClass('closed');if(Y.UA.ie>0){Y.one('body').setStyle('backgroundPosition','center 0px');headerBar.setStyle('marginTop','-40px');}else{Y.one('body').transition({'backgroundPosition':'center 0px','duration':'0.5'});headerBar.transition({'duration':'0.5','marginTop':'-40px'});}
Y.Cookie.set('navigationTeamsDDOpen','false',{path:"/",domain:".nfl.com",expires:nextMonth});}},'.team-sites-header-bar-dd-tab');Y.one('body').prepend(headerBar);new Y.SkipLinks({links:[{id:'main-nav',label:'Skip to Main navigation'},{id:'doc',label:'Skip to Main content'},{id:'footer-2012',label:'Skip to footer'}]});headerBar.delegate("click",(function(e){var linkNode,linkText,linkValue,s_analytics;linkNode=e.currentTarget;linkText=linkNode.getAttribute("class");linkValue="tn-top-team-bar-"+linkText+"_"+navType;s_analytics=s_gi(s_account);s_analytics.tl(this,'o',linkText,{linkTrackVars:"events,eVar12",linkTrackEvents:"event50",events:"event50",eVar12:linkValue});}),"a");});};}),"1.0.0",{requires:["node","array-extras","data-teams","transition","anim","skip-links"]});}).call(this);